# Generated by Django 3.2.4 on 2022-01-20 20:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('about_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Профессиональная покраска мебели, изделий из дерева и других материалов', max_length=1000, null=True)),
                ('location', models.TextField(default='140186, Московская обл., г. Люберцы, деревня Токарево, ул. Петровское поле, д. 1', max_length=1000)),
                ('email', models.EmailField(blank=True, default='info@pokraska24.com', max_length=254)),
                ('phone', models.CharField(default='(+7) 495 508-63-45', max_length=20)),
                ('phone1', models.CharField(default='(+7) 925 508-63-45', max_length=20)),
                ('work_time', models.CharField(blank=True, default='с 11 до 18 часов', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Ünvan',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=80)),
                ('phone', models.CharField(max_length=120)),
                ('content', models.TextField(max_length=10000)),
                ('checkbox', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('checkbox', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('yaer_work', models.CharField(blank=True, max_length=120, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('index_image', models.ImageField(upload_to='index_image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='ourwork')),
            ],
            options={
                'verbose_name_plural': 'OurWork',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('process_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_head_content', models.CharField(blank=True, max_length=300, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('service_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price_content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('service_image', models.ImageField(upload_to='service_image')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('service', models.ManyToManyField(blank=True, db_index=True, default=None, related_name='service_title', to='core.Service')),
            ],
            options={
                'verbose_name_plural': 'ServiceCategories',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=300, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=120)),
                ('text', models.TextField(max_length=10000)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('checkbox', models.BooleanField()),
                ('order_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_options', to='core.orderoption')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='core.about')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='core.service')),
            ],
        ),
    ]
